disabled_rules: # rule identifiers to exclude from running
  # - colon
  # - comma
  # - control_statement
  - trailing_whitespace
  # - identifier_name
  # - type_name
  # - force_cast
  # - legacy_constructor
  # - cyclomatic_complexity
  # - function_body_length

opt_in_rules: # some rules are only opt-in
  - empty_count
  # - empty_string
  # - missing_docs

# Find all the available rules by running:
# swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  # - Source

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Les_11_Networking/Models/UserModels.swift
  # - Source/ExcludedFolder
  # - Source/ExcludedFile.swift
  # - Source/*/ExcludedFile.swift
  # - Pods/RxSwift/RxSwift/Schedulers
  # - Pods/RxSwift/RxSwift/Schedulers/CurrentThreadScheduler.

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file

# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length:
  warning: 110  
  # error: 200
  ignores_comments: true
  # ignores_function_declarations: true
  # ignores_interpolated_strings: true
  # ignores_urls: true

# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error

# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
  # ignore_comment_only_lines: true

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string

identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

# function_body_length:
#     warning: 300
#     error: 500

# function_parameter_count:
#     warning: 6
#     error: 8

# cyclomatic_complexity:
#     warning: 15
#     error: 25

# warning_threshold: 15    

# reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: "xcode" 

# Id insted ID
# custom_rules:
#   id_suffix_naming:
#     name: "Wrong name"
#     regex: "(ID)"
#     match_kinds:
#       - comment
#       - identifier
#     message: "Use 'Id' instead 'ID'"
#     severity: error
